task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 1 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-train/images
    ann_file: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-train/annotations/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 8
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-val/images
    ann_file: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-val/annotations/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 8
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction

# # test
# val_dataloader:
#   type: DataLoader
#   dataset:
#     type: CocoDetection
#     img_folder: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-test-dev/images
#     ann_file: /home/adminpc/workspace/dataset/dataset_cotton/cotton-DET-test-dev/annotations/test.json
#     return_masks: False
#     transforms:
#       type: Compose
#       ops: ~
#   shuffle: False
#   num_workers: 8
#   drop_last: False
#   collate_fn:
#     type: BatchImageCollateFunction
